### ISSUE TITLE
借鉴大佬中的Permission工具 发现一个小问题

### ISSUE THREAD

**Issue by QinjianXuan** [ShonLin/QuickDevFramework#4]
/**
     * 检查是否需要RuntimePermission，即 System API >= API 23
     * */
    private static boolean checkHigherThanMarshmallow() {
        return Build.VERSION.SDK_INT > Build.VERSION_CODES.M;
    }
少了个=号  正好碰到版本23的测试机 ^-^

**Comment by ShonLin** [comment]
感谢指出，开发中的疏忽，下次提交中将会修复
