### ISSUE TITLE
关于生命周期绑定的问题

### ISSUE THREAD

**Issue by jaxhuan** [ShonLin/QuickDevFramework#6]
你好，我现在在项目中使用到你这个框架，关于生命周期绑定这一块有疑惑，方便联系研讨一下吗?

**Comment by ShonLin** [comment]
hello, 请描述一下问题？我会尽力讲解

**Comment by jaxhuan** [comment]
按照我的理解，项目是通过rx-lifecycle2来绑定manager和fragment/activity的生命周期，我在sample里面找不到调用bindUntilEvent/bindToLifecycle的代码，那是通过什么方式绑定生命周期来保证不会内存泄露的呢？抱歉，如果有表述不清的地方，留一下联系方式方便一些。

**Comment by ShonLin** [comment]
[BaseActivity](https://github.com/ShonLin/QuickDevFramework/blob/master/framework/src/main/java/com/linxiao/framework/activity/BaseActivity.java)
[BaseFragment](https://github.com/ShonLin/QuickDevFramework/blob/master/framework/src/main/java/com/linxiao/framework/fragment/BaseFragment.java)
可以看下目前框架内的基类都是直接继承带有RxLifecycle生命周期的基类的，你让自己的fragment/activity继承framework里面的基类就可以了。
对于manager来说，它只做数据请求和返回数据的变换，至于是否接受数据，应该由UI层决定，所以在我的设想中对于DataManager来说应该是不用关心生命周期的，也就是说在UI内请求数据差不多是这个样子  
```
// data manager内数据请求的定义
class DataManager extends BaseDataManager {

    public Observable<Data> requestData() {
        return NetworkManager.getClientApi().requestData()
        .map(new Function<Data, Data>() {
            @Override
            public Integer apply(@NonNull Data data) {
                // do something like handle cache
                return data;
            }
        });
    }
}

// 在Activity/Fragment调用时大概这样写
dataManager.requestData()
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
.compose(bindToLifecycler()) // 这里绑定生命周期
.subscribe(......);
```

**Comment by jaxhuan** [comment]
好的，豁然开朗，谢谢
